# Generated by Django 2.1.7 on 2020-01-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='Priority',
            field=models.CharField(max_length=30, verbose_name='Priorytet'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='Type',
            field=models.CharField(max_length=30, verbose_name='Rodzaj'),
        ),
    ]
