# Generated by Django 2.1.7 on 2020-01-09 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TaskList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='Priority',
            field=models.DateField(default='', verbose_name='Priorytet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='Type',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Rodzaj'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasks',
            name='Date',
            field=models.DateField(verbose_name='Data'),
        ),
    ]
